# Generated by Django 5.1.4 on 2026-05-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFQDropdownGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RFQ Dropdown Group',
                'verbose_name_plural': 'RFQ Dropdown Groups',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RFQDropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quote.rfqdropdowngroup')),
            ],
            options={
                'verbose_name': 'RFQ Dropdown Option',
                'verbose_name_plural': 'RFQ Dropdown Options',
                'ordering': ['order', 'id'],
            },
        ),
    ]
