# Generated by Django 5.1.4 on 2026-05-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('badge_text', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('meta_one', models.CharField(blank=True, default='', max_length=120)),
                ('meta_two', models.CharField(blank=True, default='', max_length=120)),
                ('meta_three', models.CharField(blank=True, default='', max_length=120)),
                ('primary_button_text', models.CharField(blank=True, default='', max_length=100)),
                ('primary_button_link', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, default='', max_length=100)),
                ('secondary_button_link', models.CharField(blank=True, default='', max_length=255)),
                ('visual_label', models.CharField(blank=True, default='', max_length=200)),
                ('visual_title', models.CharField(blank=True, default='', max_length=200)),
                ('visual_description', models.TextField(blank=True, default='')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='quote/hero/')),
                ('background_image_mobile', models.ImageField(blank=True, help_text='Optional mobile-specific hero image.', null=True, upload_to='quote/hero/mobile/')),
                ('overlay_opacity', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Overlay strength between 0.00 and 1.00', max_digits=3, null=True)),
                ('text_color', models.CharField(blank=True, default='', max_length=20)),
                ('accent_color', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Hero Section',
                'verbose_name_plural': 'Quote Hero Sections',
                'ordering': ['order', '-created_at', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='rfqdropdowngroup',
            name='key',
            field=models.SlugField(blank=True, help_text='Example: typology, site_status, services, budget, referral', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rfqdropdowngroup',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rfqdropdowngroup',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='rfqdropdownoption',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quote.rfqdropdowngroup'),
        ),
        migrations.AlterField(
            model_name='rfqdropdownoption',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rfqdropdownoption',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
