# Generated by Django 5.1.4 on 2026-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_quoteherosection_alter_rfqdropdowngroup_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typology', models.CharField(max_length=100)),
                ('site_status', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('referral', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('scale', models.CharField(blank=True, max_length=100, null=True)),
                ('vision_narrative', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RFQ Lead',
                'verbose_name_plural': 'RFQ Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
