# Generated by Django 5.1.4 on 2026-05-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_rfqlead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RFQLead',
        ),
    ]
