# Generated by Django 5.1.4 on 2026-05-06 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, default='#080808', max_length=20)),
                ('border_color', models.CharField(blank=True, default='#1a1a1a', max_length=20)),
                ('text_color', models.CharField(blank=True, default='#f4f4f0', max_length=20)),
                ('muted_color', models.CharField(blank=True, default='#8a8a8a', max_length=20)),
                ('accent_color', models.CharField(blank=True, default='#b89768', max_length=20)),
                ('font_ui', models.CharField(blank=True, choices=[("'Inter', sans-serif", 'Inter'), ("'Playfair Display', serif", 'Playfair Display'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Roboto', sans-serif", 'Roboto'), ("'Poppins', sans-serif", 'Poppins'), ("'Lato', sans-serif", 'Lato'), ("'Open Sans', sans-serif", 'Open Sans'), ("'Source Sans 3', sans-serif", 'Source Sans 3')], default="'Inter', sans-serif", max_length=100)),
                ('font_display', models.CharField(blank=True, choices=[("'Inter', sans-serif", 'Inter'), ("'Playfair Display', serif", 'Playfair Display'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Roboto', sans-serif", 'Roboto'), ("'Poppins', sans-serif", 'Poppins'), ("'Lato', sans-serif", 'Lato'), ("'Open Sans', sans-serif", 'Open Sans'), ("'Source Sans 3', sans-serif", 'Source Sans 3')], default="'Playfair Display', serif", max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_description', models.TextField(blank=True, default='')),
                ('projects_heading', models.CharField(blank=True, default='Projects', max_length=50)),
                ('practice_heading', models.CharField(blank=True, default='Practice', max_length=50)),
                ('subscription_heading', models.CharField(blank=True, default='Subscription', max_length=50)),
                ('newsletter_text', models.TextField(blank=True, default='Sign up to receive our biannual curation of architectural insights.')),
                ('newsletter_placeholder', models.CharField(blank=True, default='Email Address', max_length=100)),
                ('newsletter_button_text', models.CharField(blank=True, default='Join', max_length=50)),
                ('newsletter_action_url', models.CharField(blank=True, default='#', max_length=255)),
                ('copyright_text', models.CharField(blank=True, default='', max_length=255)),
                ('bottom_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('space-between', 'Space Between')], default='space-between', max_length=20)),
                ('social_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=20)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='footer/logo/')),
                ('logo_alt', models.CharField(blank=True, default='', max_length=255)),
                ('logo_url', models.CharField(blank=True, default='/', max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_bg_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('nav_text_color', models.CharField(blank=True, default='#6b7280', max_length=20)),
                ('nav_text_dark', models.CharField(blank=True, default='#111827', max_length=20)),
                ('nav_hover_color', models.CharField(blank=True, default='#111827', max_length=20)),
                ('nav_border_color', models.CharField(blank=True, default='rgba(0, 0, 0, 0.08)', max_length=30)),
                ('nav_font_family', models.CharField(blank=True, choices=[("'Inter', sans-serif", 'Inter'), ("'Playfair Display', serif", 'Playfair Display'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Roboto', sans-serif", 'Roboto'), ("'Poppins', sans-serif", 'Poppins'), ("'Lato', sans-serif", 'Lato'), ("'Open Sans', sans-serif", 'Open Sans'), ("'Source Sans 3', sans-serif", 'Source Sans 3')], default="'Inter', sans-serif", max_length=100)),
                ('nav_padding_y', models.PositiveIntegerField(default=12)),
                ('nav_padding_x', models.PositiveIntegerField(default=20)),
                ('nav_logo_height', models.PositiveIntegerField(default=40)),
            ],
            options={
                'verbose_name': 'Navbar Settings',
                'verbose_name_plural': 'Navbar Settings',
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Logo',
                'verbose_name_plural': 'Site Logo',
            },
        ),
        migrations.CreateModel(
            name='FooterProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='core.footersettings')),
            ],
            options={
                'verbose_name': 'Footer Project Link',
                'verbose_name_plural': 'Footer Project Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterPracticeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_links', to='core.footersettings')),
            ],
            options={
                'verbose_name': 'Footer Practice Link',
                'verbose_name_plural': 'Footer Practice Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('icon_name', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('facebook', 'Facebook'), ('custom', 'Custom SVG')], default='instagram', max_length=20)),
                ('icon_svg', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.footersettings')),
            ],
            options={
                'verbose_name': 'Footer Social Link',
                'verbose_name_plural': 'Footer Social Links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
