# Generated by Django 5.1.4 on 2026-05-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='type',
            field=models.CharField(choices=[('link', 'Link'), ('cta', 'CTA Button')], default='link', max_length=10),
        ),
    ]
