# Generated by Django 5.1.4 on 2026-05-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_navitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroTypographySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Home Hero'), ('about', 'About Hero'), ('project', 'Project Hero'), ('interior', 'Interior Hero'), ('services', 'Services Hero'), ('blog', 'Blog Hero'), ('contact', 'Contact Hero')], max_length=50, unique=True)),
                ('title_font_family', models.CharField(choices=[("'Open Sans', sans-serif", 'Open Sans'), ("'Roboto', sans-serif", 'Roboto'), ("'Work Sans', sans-serif", 'Work Sans'), ("'Lato', sans-serif", 'Lato'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Poppins', sans-serif", 'Poppins'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Merriweather', serif", 'Merriweather'), ("'Playfair Display', serif", 'Playfair Display'), ("'Lora', serif", 'Lora'), ("'Source Serif 4', serif", 'Source Serif 4'), ("'Inter', sans-serif", 'Inter'), ("'Josefin Sans', sans-serif", 'Josefin Sans'), ("'Rubik', sans-serif", 'Rubik'), ("'DM Sans', sans-serif", 'DM Sans'), ("'Nunito', sans-serif", 'Nunito'), ("'Ubuntu', sans-serif", 'Ubuntu'), ("'Ranade', sans-serif", 'Ranade'), ("'Source Sans Pro', sans-serif", 'Source Sans Pro')], default="'Playfair Display', serif", max_length=255)),
                ('title_font_type', models.CharField(choices=[('sans-serif', 'Sans Serif'), ('serif', 'Serif'), ('display', 'Display')], default='display', max_length=50)),
                ('title_font_weight', models.CharField(choices=[('100', 'Thin 100'), ('200', 'Extra Light 200'), ('300', 'Light 300'), ('400', 'Regular 400'), ('500', 'Medium 500'), ('600', 'Semi Bold 600'), ('700', 'Bold 700'), ('800', 'Extra Bold 800'), ('900', 'Black 900')], default='600', max_length=10)),
                ('title_font_size_desktop', models.CharField(default='6rem', max_length=20)),
                ('title_font_size_tablet', models.CharField(default='4.5rem', max_length=20)),
                ('title_font_size_mobile', models.CharField(default='3rem', max_length=20)),
                ('title_line_height', models.CharField(default='0.96', max_length=20)),
                ('title_letter_spacing', models.CharField(default='-0.04em', max_length=20)),
                ('title_text_transform', models.CharField(choices=[('none', 'None'), ('uppercase', 'Uppercase'), ('lowercase', 'Lowercase'), ('capitalize', 'Capitalize')], default='none', max_length=20)),
                ('title_color', models.CharField(default='#ffffff', max_length=50)),
                ('body_font_family', models.CharField(choices=[("'Open Sans', sans-serif", 'Open Sans'), ("'Roboto', sans-serif", 'Roboto'), ("'Work Sans', sans-serif", 'Work Sans'), ("'Lato', sans-serif", 'Lato'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Poppins', sans-serif", 'Poppins'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Merriweather', serif", 'Merriweather'), ("'Playfair Display', serif", 'Playfair Display'), ("'Lora', serif", 'Lora'), ("'Source Serif 4', serif", 'Source Serif 4'), ("'Inter', sans-serif", 'Inter'), ("'Josefin Sans', sans-serif", 'Josefin Sans'), ("'Rubik', sans-serif", 'Rubik'), ("'DM Sans', sans-serif", 'DM Sans'), ("'Nunito', sans-serif", 'Nunito'), ("'Ubuntu', sans-serif", 'Ubuntu'), ("'Ranade', sans-serif", 'Ranade'), ("'Source Sans Pro', sans-serif", 'Source Sans Pro')], default="'Inter', sans-serif", max_length=255)),
                ('body_font_type', models.CharField(choices=[('sans-serif', 'Sans Serif'), ('serif', 'Serif'), ('display', 'Display')], default='sans-serif', max_length=50)),
                ('body_font_weight', models.CharField(choices=[('100', 'Thin 100'), ('200', 'Extra Light 200'), ('300', 'Light 300'), ('400', 'Regular 400'), ('500', 'Medium 500'), ('600', 'Semi Bold 600'), ('700', 'Bold 700'), ('800', 'Extra Bold 800'), ('900', 'Black 900')], default='400', max_length=10)),
                ('body_font_size_desktop', models.CharField(default='1.15rem', max_length=20)),
                ('body_font_size_tablet', models.CharField(default='1.05rem', max_length=20)),
                ('body_font_size_mobile', models.CharField(default='1rem', max_length=20)),
                ('body_line_height', models.CharField(default='1.7', max_length=20)),
                ('body_letter_spacing', models.CharField(default='0em', max_length=20)),
                ('body_text_transform', models.CharField(choices=[('none', 'None'), ('uppercase', 'Uppercase'), ('lowercase', 'Lowercase'), ('capitalize', 'Capitalize')], default='none', max_length=20)),
                ('body_color', models.CharField(default='rgba(255,255,255,0.82)', max_length=50)),
                ('button_font_family', models.CharField(choices=[("'Open Sans', sans-serif", 'Open Sans'), ("'Roboto', sans-serif", 'Roboto'), ("'Work Sans', sans-serif", 'Work Sans'), ("'Lato', sans-serif", 'Lato'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Poppins', sans-serif", 'Poppins'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Merriweather', serif", 'Merriweather'), ("'Playfair Display', serif", 'Playfair Display'), ("'Lora', serif", 'Lora'), ("'Source Serif 4', serif", 'Source Serif 4'), ("'Inter', sans-serif", 'Inter'), ("'Josefin Sans', sans-serif", 'Josefin Sans'), ("'Rubik', sans-serif", 'Rubik'), ("'DM Sans', sans-serif", 'DM Sans'), ("'Nunito', sans-serif", 'Nunito'), ("'Ubuntu', sans-serif", 'Ubuntu'), ("'Ranade', sans-serif", 'Ranade'), ("'Source Sans Pro', sans-serif", 'Source Sans Pro')], default="'Inter', sans-serif", max_length=255)),
                ('button_font_weight', models.CharField(choices=[('100', 'Thin 100'), ('200', 'Extra Light 200'), ('300', 'Light 300'), ('400', 'Regular 400'), ('500', 'Medium 500'), ('600', 'Semi Bold 600'), ('700', 'Bold 700'), ('800', 'Extra Bold 800'), ('900', 'Black 900')], default='500', max_length=10)),
                ('button_font_size', models.CharField(default='0.95rem', max_length=20)),
                ('button_letter_spacing', models.CharField(default='0.01em', max_length=20)),
                ('button_text_transform', models.CharField(choices=[('none', 'None'), ('uppercase', 'Uppercase'), ('lowercase', 'Lowercase'), ('capitalize', 'Capitalize')], default='none', max_length=20)),
                ('button_color', models.CharField(default='#ffffff', max_length=50)),
                ('stats_font_family', models.CharField(choices=[("'Open Sans', sans-serif", 'Open Sans'), ("'Roboto', sans-serif", 'Roboto'), ("'Work Sans', sans-serif", 'Work Sans'), ("'Lato', sans-serif", 'Lato'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Poppins', sans-serif", 'Poppins'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Merriweather', serif", 'Merriweather'), ("'Playfair Display', serif", 'Playfair Display'), ("'Lora', serif", 'Lora'), ("'Source Serif 4', serif", 'Source Serif 4'), ("'Inter', sans-serif", 'Inter'), ("'Josefin Sans', sans-serif", 'Josefin Sans'), ("'Rubik', sans-serif", 'Rubik'), ("'DM Sans', sans-serif", 'DM Sans'), ("'Nunito', sans-serif", 'Nunito'), ("'Ubuntu', sans-serif", 'Ubuntu'), ("'Ranade', sans-serif", 'Ranade'), ("'Source Sans Pro', sans-serif", 'Source Sans Pro')], default="'Inter', sans-serif", max_length=255)),
                ('stats_font_weight', models.CharField(choices=[('100', 'Thin 100'), ('200', 'Extra Light 200'), ('300', 'Light 300'), ('400', 'Regular 400'), ('500', 'Medium 500'), ('600', 'Semi Bold 600'), ('700', 'Bold 700'), ('800', 'Extra Bold 800'), ('900', 'Black 900')], default='600', max_length=10)),
                ('stats_font_size', models.CharField(default='2rem', max_length=20)),
                ('stats_color', models.CharField(default='#ffffff', max_length=50)),
                ('panel_font_family', models.CharField(choices=[("'Open Sans', sans-serif", 'Open Sans'), ("'Roboto', sans-serif", 'Roboto'), ("'Work Sans', sans-serif", 'Work Sans'), ("'Lato', sans-serif", 'Lato'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Poppins', sans-serif", 'Poppins'), ("'Raleway', sans-serif", 'Raleway'), ("'Oswald', sans-serif", 'Oswald'), ("'Merriweather', serif", 'Merriweather'), ("'Playfair Display', serif", 'Playfair Display'), ("'Lora', serif", 'Lora'), ("'Source Serif 4', serif", 'Source Serif 4'), ("'Inter', sans-serif", 'Inter'), ("'Josefin Sans', sans-serif", 'Josefin Sans'), ("'Rubik', sans-serif", 'Rubik'), ("'DM Sans', sans-serif", 'DM Sans'), ("'Nunito', sans-serif", 'Nunito'), ("'Ubuntu', sans-serif", 'Ubuntu'), ("'Ranade', sans-serif", 'Ranade'), ("'Source Sans Pro', sans-serif", 'Source Sans Pro')], default="'Inter', sans-serif", max_length=255)),
                ('panel_font_weight', models.CharField(choices=[('100', 'Thin 100'), ('200', 'Extra Light 200'), ('300', 'Light 300'), ('400', 'Regular 400'), ('500', 'Medium 500'), ('600', 'Semi Bold 600'), ('700', 'Bold 700'), ('800', 'Extra Bold 800'), ('900', 'Black 900')], default='400', max_length=10)),
                ('panel_font_size', models.CharField(default='1rem', max_length=20)),
                ('panel_line_height', models.CharField(default='1.7', max_length=20)),
                ('panel_letter_spacing', models.CharField(default='0em', max_length=20)),
                ('panel_text_transform', models.CharField(choices=[('none', 'None'), ('uppercase', 'Uppercase'), ('lowercase', 'Lowercase'), ('capitalize', 'Capitalize')], default='none', max_length=20)),
                ('panel_color', models.CharField(default='#ffffff', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Typography Setting',
                'verbose_name_plural': 'Hero Typography Settings',
                'ordering': ['page_type'],
            },
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='font_display',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='font_ui',
        ),
        migrations.RemoveField(
            model_name='navbarsettings',
            name='nav_font_family',
        ),
    ]
