# Generated by Django 5.1.4 on 2026-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_herotypographysettings_button_font_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='9779802113456', help_text='WhatsApp number with country code (no +, no spaces)', max_length=20)),
                ('prefilled_text', models.TextField(default='Hello! I would like to get more information about your services.', help_text='Default WhatsApp message')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Settings',
                'verbose_name_plural': 'WhatsApp Settings',
            },
        ),
    ]
