# Generated by Django 5.1.4 on 2026-05-16 05:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('email_address', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('project_details', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('source_page', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('page_title', models.CharField(blank=True, default='Premium Contact Us', max_length=200)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('hero_badge', models.CharField(blank=True, default='Premium Architecture Studio', max_length=120)),
                ('hero_title', models.CharField(blank=True, default='Contact Us', max_length=200)),
                ('hero_description', models.TextField(blank=True, default='Reach out for architecture, interior design, consultation, renovation, planning, or project collaboration. We create modern premium spaces with timeless aesthetics.')),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='contact/hero/')),
                ('hero_overlay_strength', models.PositiveSmallIntegerField(blank=True, default=55, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('top_cards_heading', models.CharField(blank=True, default='', max_length=150)),
                ('top_cards_subheading', models.TextField(blank=True, default='')),
                ('left_section_badge', models.CharField(blank=True, default='Premium Support', max_length=120)),
                ('left_section_title', models.CharField(blank=True, default="Let's Build Something Beautiful", max_length=200)),
                ('left_section_description', models.TextField(blank=True, default='Share your ideas and project requirements with us. We provide architecture, interior design, planning, consultation, and renovation services with premium quality.')),
                ('left_section_background_image', models.ImageField(blank=True, null=True, upload_to='contact/left_panel/')),
                ('form_title', models.CharField(blank=True, default='Send Inquiry', max_length=200)),
                ('form_subtitle', models.TextField(blank=True, default='Fill the form below and our team will contact you shortly.')),
                ('submit_button_text', models.CharField(blank=True, default='Start Your Project', max_length=120)),
                ('success_message', models.CharField(blank=True, default='Thank you! Your inquiry has been submitted successfully.', max_length=255)),
                ('map_title', models.CharField(blank=True, default='Visit Our Studio', max_length=200)),
                ('map_description', models.TextField(blank=True, default='Experience modern architecture and premium interior solutions.')),
                ('map_embed_url', models.CharField(blank=True, default='', max_length=1000)),
                ('map_location_text', models.CharField(blank=True, default='Kathmandu, Nepal', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=100)),
                ('contact_location', models.CharField(blank=True, default='', max_length=255)),
                ('contact_address', models.CharField(blank=True, default='', max_length=255)),
                ('social_heading', models.CharField(blank=True, default='', max_length=150)),
                ('instagram_url', models.CharField(blank=True, default='', max_length=500)),
                ('facebook_url', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_text', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_boxes', to='contact.contactpagesettings')),
            ],
            options={
                'verbose_name': 'Contact Info Box',
                'verbose_name_plural': 'Contact Info Boxes',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('icon_text', models.CharField(blank=True, default='', max_length=20)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='contact.contactpagesettings')),
            ],
            options={
                'verbose_name': 'Contact Social Link',
                'verbose_name_plural': 'Contact Social Links',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactTopCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_text', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_cards', to='contact.contactpagesettings')),
            ],
            options={
                'verbose_name': 'Contact Top Card',
                'verbose_name_plural': 'Contact Top Cards',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
