# Generated by Django 5.1.4 on 2026-05-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('is_active', models.BooleanField(default=True, help_text='Show on the Services page')),
                ('show_on_home', models.BooleanField(default=False, help_text='Show on the homepage services section')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'id'],
            },
        ),
    ]
