# Generated by Django 5.1.4 on 2026-05-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(blank=True, help_text='Small top label (e.g. Premium Architecture Services)', max_length=120, null=True)),
                ('title', models.CharField(blank=True, help_text='Main hero heading', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Hero description paragraph', null=True)),
                ('btn_primary_text', models.CharField(blank=True, max_length=80, null=True)),
                ('btn_primary_link', models.CharField(blank=True, max_length=255, null=True)),
                ('btn_secondary_text', models.CharField(blank=True, max_length=80, null=True)),
                ('btn_secondary_link', models.CharField(blank=True, max_length=255, null=True)),
                ('stat_1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('stat_2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('stat_3_text', models.CharField(blank=True, max_length=255, null=True)),
                ('stat_4_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services Hero Section',
                'verbose_name_plural': 'Services Hero Section',
            },
        ),
    ]
