# Generated by Django 5.1.4 on 2026-05-15 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicesherosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_text', models.CharField(blank=True, default='Crafted for impact', max_length=120, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('card_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('card_description', models.TextField(blank=True, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='services/why_choose/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.whychoosesection')),
            ],
            options={
                'verbose_name': 'Why Choose Feature',
                'verbose_name_plural': 'Why Choose Features',
                'ordering': ['id'],
            },
        ),
    ]
