# Generated by Django 5.1.4 on 2026-05-16 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_whychoosesection_whychoosefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesExtraSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Services Extra Section',
                'verbose_name_plural': 'Services Extra Sections',
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='services.servicesextrasection')),
            ],
            options={
                'verbose_name': 'Service Process Step',
                'verbose_name_plural': 'Service Process Steps',
            },
        ),
        migrations.CreateModel(
            name='ServiceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='services.servicesextrasection')),
            ],
            options={
                'verbose_name': 'Service Metric',
                'verbose_name_plural': 'Service Metrics',
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='', max_length=255)),
                ('answer', models.TextField(blank=True, default='')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.servicesextrasection')),
            ],
            options={
                'verbose_name': 'Service FAQ',
                'verbose_name_plural': 'Service FAQs',
            },
        ),
        migrations.CreateModel(
            name='ServiceCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('primary_button_text', models.CharField(blank=True, default='', max_length=100)),
                ('secondary_button_text', models.CharField(blank=True, default='', max_length=100)),
                ('section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='services.servicesextrasection')),
            ],
            options={
                'verbose_name': 'Service CTA',
                'verbose_name_plural': 'Service CTA',
            },
        ),
        migrations.CreateModel(
            name='ServiceSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/spotlight/')),
                ('section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spotlight', to='services.servicesextrasection')),
            ],
            options={
                'verbose_name': 'Service Spotlight',
                'verbose_name_plural': 'Service Spotlight',
            },
        ),
        migrations.CreateModel(
            name='ServiceSpotlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spotlight_items', to='services.servicesextrasection')),
            ],
            options={
                'verbose_name': 'Service Spotlight Item',
                'verbose_name_plural': 'Service Spotlight Items',
            },
        ),
    ]
