# Generated by Django 5.1.4 on 2026-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicesextrasection_serviceprocessstep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicefaq',
            options={'ordering': ['id'], 'verbose_name': 'Service FAQ', 'verbose_name_plural': 'Service FAQs'},
        ),
        migrations.AlterModelOptions(
            name='servicemetric',
            options={'ordering': ['id'], 'verbose_name': 'Service Metric', 'verbose_name_plural': 'Service Metrics'},
        ),
        migrations.AlterModelOptions(
            name='serviceprocessstep',
            options={'ordering': ['number', 'id'], 'verbose_name': 'Service Process Step', 'verbose_name_plural': 'Service Process Steps'},
        ),
        migrations.AlterModelOptions(
            name='servicespotlightitem',
            options={'ordering': ['id'], 'verbose_name': 'Service Spotlight Item', 'verbose_name_plural': 'Service Spotlight Items'},
        ),
        migrations.AddField(
            model_name='servicecta',
            name='primary_button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecta',
            name='secondary_button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='faq_label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='faq_side_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='faq_side_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='faq_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='faq_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='metrics_label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='metrics_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='metrics_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='process_label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='process_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesextrasection',
            name='process_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicespotlight',
            name='primary_button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicespotlight',
            name='primary_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicespotlight',
            name='secondary_button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicespotlight',
            name='secondary_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicecta',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecta',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicecta',
            name='primary_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicecta',
            name='secondary_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicecta',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicemetric',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicemetric',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicemetric',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicesextrasection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicespotlight',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicespotlight',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicespotlight',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicespotlightitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicespotlightitem',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicespotlightitem',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
