# Generated by Django 5.1.4 on 2026-05-17 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicefaq_options_alter_servicemetric_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecta',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='services.servicesextrasection'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.servicesextrasection'),
        ),
        migrations.AlterField(
            model_name='servicemetric',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='services.servicesextrasection'),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='services.servicesextrasection'),
        ),
        migrations.AlterField(
            model_name='servicespotlight',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotlight', to='services.servicesextrasection'),
        ),
        migrations.AlterField(
            model_name='servicespotlightitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlight_items', to='services.servicesextrasection'),
        ),
    ]
