# Generated by Django 5.1.4 on 2026-05-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicecta_section_alter_servicefaq_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesherosection',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero background image', null=True, upload_to='services/hero/'),
        ),
    ]
