# Generated by Django 5.1.4 on 2026-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicesherosection_hero_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whychoosesection',
            options={'verbose_name': 'Why Choose Section', 'verbose_name_plural': 'Why Choose Section'},
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(max_length=255, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicesherosection',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero background image', max_length=255, null=True, upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='servicespotlight',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='services/spotlight/'),
        ),
        migrations.AlterField(
            model_name='whychoosesection',
            name='card_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='services/why_choose/'),
        ),
    ]
