# Generated by Django 5.1.4 on 2026-05-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHeaderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Perspectives', help_text='Small uppercase label above the main heading.', max_length=100)),
                ('title', models.CharField(default='The Journal', help_text='Main hero heading text.', max_length=200)),
                ('description', models.TextField(default='Exploring the intersection of architectural minimalism, honest materials, and the future of human-centric design.', help_text='Hero section description text.')),
                ('background_image', models.ImageField(help_text='Hero background image for the blog header section.', upload_to='blogs/header/')),
                ('is_active', models.BooleanField(default=True, help_text='Enable this header section on the blog page.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Header Section',
                'verbose_name_plural': 'Blog Header Sections',
            },
        ),
    ]
