# Generated by Django 5.1.4 on 2026-05-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Author name shown in the sidebar and post meta.', max_length=150)),
                ('designation', models.CharField(help_text='Author role or designation.', max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Short author bio.')),
                ('profile_image', models.ImageField(blank=True, help_text='Author profile image.', null=True, upload_to='blogs/authors/')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL.')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL.')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL.')),
            ],
            options={
                'verbose_name': 'Blog Author',
                'verbose_name_plural': 'Blog Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name shown on blog posts.', max_length=120, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly category slug.', max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPageIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_label', models.CharField(default='Volume 04 — 2026', help_text='Small volume label above the blog page intro heading.', max_length=100)),
                ('heading', models.CharField(default='Perspectives', help_text='Main blog listing heading.', max_length=200)),
                ('description', models.TextField(default='Curated thoughts on architectural minimalism, sustainable form, and the future of structural storytelling.', help_text='Intro description shown on the blog listing page.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable this intro section on the blog page.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Page Intro',
                'verbose_name_plural': 'Blog Page Intros',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name shown in the post sidebar.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly tag slug.', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title.', max_length=250)),
                ('slug', models.SlugField(help_text='URL-friendly blog post slug.', max_length=280, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown in listing cards and featured post.')),
                ('content', models.TextField(help_text='Full blog post content.')),
                ('featured_image', models.ImageField(help_text='Main featured image for the post.', upload_to='blogs/posts/')),
                ('read_time', models.CharField(blank=True, help_text="Read time label such as '8 Min Read'.", max_length=50)),
                ('published_date', models.DateField(help_text='Date shown in the listing and detail pages.')),
                ('is_featured', models.BooleanField(default=False, help_text='Marks this post as the featured post on the blog listing page.')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='If enabled, this post will appear in the homepage blog section.')),
                ('is_published', models.BooleanField(default=True, help_text='Show this post on the blog page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='Post author.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blogs.blogauthor')),
                ('category', models.ForeignKey(blank=True, help_text='Post category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blogs.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for this post.', related_name='posts', to='blogs.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
