# Generated by Django 5.1.4 on 2026-05-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogauthor_blogcategory_blogpageintro_blogtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short author bio.'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Author role or designation.', max_length=150),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='Instagram profile URL.'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', help_text='LinkedIn profile URL.'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Author name shown in the sidebar and post meta.', max_length=150),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='twitter_url',
            field=models.URLField(blank=True, default='', help_text='Twitter/X profile URL.'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Category name shown on blog posts.', max_length=120),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly category slug.', max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogheadersection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Hero background image for the blog header section.', null=True, upload_to='blogs/header/'),
        ),
        migrations.AlterField(
            model_name='blogheadersection',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Hero section description text.'),
        ),
        migrations.AlterField(
            model_name='blogheadersection',
            name='eyebrow',
            field=models.CharField(blank=True, default='', help_text='Small uppercase label above the main heading.', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogheadersection',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Main hero heading text.', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpageintro',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Intro description shown on the blog listing page.'),
        ),
        migrations.AlterField(
            model_name='blogpageintro',
            name='heading',
            field=models.CharField(blank=True, default='', help_text='Main blog listing heading.', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpageintro',
            name='volume_label',
            field=models.CharField(blank=True, default='', help_text='Small volume label above the blog page intro heading.', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Full blog post content.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Short summary shown in listing cards and featured post.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main featured image for the post.', null=True, upload_to='blogs/posts/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateField(blank=True, help_text='Date shown in the listing and detail pages.', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, default='', help_text="Read time label such as '8 Min Read'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly blog post slug.', max_length=280, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Blog post title.', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Tag name shown in the post sidebar.', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly tag slug.', max_length=120, null=True, unique=True),
        ),
    ]
