# Generated by Django 5.1.4 on 2026-05-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_aria_label', models.CharField(blank=True, default='Premium architecture homepage banner', max_length=255)),
                ('hero_background_image', models.ImageField(blank=True, help_text='Main desktop hero background image.', null=True, upload_to='home/hero/')),
                ('hero_mobile_image', models.ImageField(blank=True, help_text='Optional separate mobile hero image.', null=True, upload_to='home/hero/mobile/')),
                ('hero_background_alt', models.CharField(blank=True, default='Homepage hero background image', max_length=255)),
                ('hero_heading', models.TextField(blank=True, default='Designing spaces\nthat feel timeless\nand profoundly modern.', help_text='Use line breaks to control the heading layout.')),
                ('hero_subheading', models.TextField(blank=True, default='A premium architecture studio shaping residential, commercial, and cultural environments with clarity, precision, and quiet confidence.')),
                ('hero_primary_cta_text', models.CharField(blank=True, default='Explore Projects', max_length=100)),
                ('hero_primary_cta_link', models.URLField(blank=True, default='')),
                ('hero_secondary_cta_text', models.CharField(blank=True, default='Book a Consultation', max_length=100)),
                ('hero_secondary_cta_link', models.URLField(blank=True, default='')),
                ('hero_stat_1_value', models.CharField(blank=True, default='120+', max_length=50)),
                ('hero_stat_1_label', models.CharField(blank=True, default='Completed works', max_length=100)),
                ('hero_stat_2_value', models.CharField(blank=True, default='18', max_length=50)),
                ('hero_stat_2_label', models.CharField(blank=True, default='Years of practice', max_length=100)),
                ('hero_stat_3_value', models.CharField(blank=True, default='9', max_length=50)),
                ('hero_stat_3_label', models.CharField(blank=True, default='Global awards', max_length=100)),
                ('featured_project_label', models.CharField(blank=True, default='Featured Project', max_length=100)),
                ('featured_project_title', models.CharField(blank=True, default='Harbor House', max_length=200)),
                ('featured_project_description', models.TextField(blank=True, default='A refined waterfront residence defined by warm materials, strong geometry, and soft daylight.')),
                ('featured_project_type', models.CharField(blank=True, default='Residential', max_length=100)),
                ('featured_project_location', models.CharField(blank=True, default='Singapore', max_length=100)),
                ('featured_project_status', models.CharField(blank=True, default='Completed', max_length=100)),
                ('featured_project_image_1', models.ImageField(blank=True, help_text='First featured project preview image.', null=True, upload_to='home/featured/')),
                ('featured_project_image_1_alt', models.CharField(blank=True, default='Minimal luxury interior with soft natural light', max_length=255)),
                ('featured_project_image_1_caption', models.CharField(blank=True, default='Interior calm', max_length=100)),
                ('featured_project_image_2', models.ImageField(blank=True, help_text='Second featured project preview image.', null=True, upload_to='home/featured/')),
                ('featured_project_image_2_alt', models.CharField(blank=True, default='Modern architectural building facade', max_length=255)),
                ('featured_project_image_2_caption', models.CharField(blank=True, default='Facade rhythm', max_length=100)),
                ('featured_project_image_3', models.ImageField(blank=True, help_text='Third featured project preview image.', null=True, upload_to='home/featured/')),
                ('featured_project_image_3_alt', models.CharField(blank=True, default='Contemporary architecture with sharp lines', max_length=255)),
                ('featured_project_image_3_caption', models.CharField(blank=True, default='Structural clarity', max_length=100)),
                ('font_ui', models.CharField(choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100)),
                ('font_display', models.CharField(choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Playfair Display, serif', max_length=100)),
                ('font_eyebrow', models.CharField(choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100)),
                ('font_title', models.CharField(choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Playfair Display, serif', max_length=100)),
                ('font_body', models.CharField(choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100)),
                ('font_panel', models.CharField(choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100)),
                ('font_stats', models.CharField(choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100)),
                ('overlay_color', models.CharField(blank=True, default='rgba(9, 10, 12, 0.45)', max_length=100)),
                ('overlay_deep_color', models.CharField(blank=True, default='rgba(9, 10, 12, 0.66)', max_length=100)),
                ('text_color', models.CharField(blank=True, default='#ffffff', max_length=50)),
                ('muted_color', models.CharField(blank=True, default='rgba(255, 255, 255, 0.78)', max_length=50)),
                ('border_color', models.CharField(blank=True, default='rgba(255, 255, 255, 0.12)', max_length=100)),
                ('card_bg_color', models.CharField(blank=True, default='rgba(255, 255, 255, 0.06)', max_length=100)),
                ('card_bg_strong_color', models.CharField(blank=True, default='rgba(255, 255, 255, 0.10)', max_length=100)),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
    ]
