# Generated by Django 5.1.4 on 2026-05-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_materialstacksection_materialstackcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RippleDifferenceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='The Ripple Difference', max_length=120)),
                ('heading', models.CharField(default='Elevating standards through visionary design.', max_length=255)),
                ('description', models.TextField(default="We don't just build structures; we curate experiences. Our studio combines rigorous technical expertise with a profound understanding of spatial psychology.")),
                ('feature_one_title', models.CharField(default='Precision Engineering', max_length=150)),
                ('feature_one_description', models.TextField(default='Every angle, joint, and material transition is calculated with obsessive attention to detail, ensuring flawless execution.')),
                ('feature_two_title', models.CharField(default='Sustainable Integration', max_length=150)),
                ('feature_two_description', models.TextField(default='We integrate passive cooling, natural lighting, and ethical materials to minimize environmental impact without sacrificing luxury.')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='home/ripple_difference/')),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='home/ripple_difference/')),
                ('button_text', models.CharField(default='Learn More About Us', max_length=80)),
                ('button_url', models.CharField(default='/about/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ripple Difference Section',
                'verbose_name_plural': 'Ripple Difference Section',
            },
        ),
    ]
