# Generated by Django 5.1.4 on 2026-05-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teamsectionsettings_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialstackcard',
            options={'ordering': ['order'], 'verbose_name': 'Material Stack Card', 'verbose_name_plural': 'Material Stack Cards'},
        ),
        migrations.AlterModelOptions(
            name='materialstacksection',
            options={'verbose_name': 'Material Stack Section', 'verbose_name_plural': 'Material Stack Section'},
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='border_color',
            field=models.CharField(blank=True, default='rgba(255, 255, 255, 0.12)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='card_bg_color',
            field=models.CharField(blank=True, default='rgba(255, 255, 255, 0.06)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='card_bg_strong_color',
            field=models.CharField(blank=True, default='rgba(255, 255, 255, 0.10)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_description',
            field=models.TextField(blank=True, default='A refined waterfront residence defined by warm materials, strong geometry, and soft daylight.', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_image_1_alt',
            field=models.CharField(blank=True, default='Minimal luxury interior with soft natural light', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_image_1_caption',
            field=models.CharField(blank=True, default='Interior calm', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_image_2_alt',
            field=models.CharField(blank=True, default='Modern architectural building facade', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_image_2_caption',
            field=models.CharField(blank=True, default='Facade rhythm', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_image_3_alt',
            field=models.CharField(blank=True, default='Contemporary architecture with sharp lines', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_image_3_caption',
            field=models.CharField(blank=True, default='Structural clarity', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_label',
            field=models.CharField(blank=True, default='Featured Project', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_location',
            field=models.CharField(blank=True, default='Singapore', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_status',
            field=models.CharField(blank=True, default='Completed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_title',
            field=models.CharField(blank=True, default='Harbor House', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_project_type',
            field=models.CharField(blank=True, default='Residential', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='font_body',
            field=models.CharField(blank=True, choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='font_display',
            field=models.CharField(blank=True, choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Playfair Display, serif', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='font_eyebrow',
            field=models.CharField(blank=True, choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='font_panel',
            field=models.CharField(blank=True, choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='font_stats',
            field=models.CharField(blank=True, choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='font_title',
            field=models.CharField(blank=True, choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Playfair Display, serif', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='font_ui',
            field=models.CharField(blank=True, choices=[('Inter, sans-serif', 'Inter'), ('Playfair Display, serif', 'Playfair Display'), ('Roboto, sans-serif', 'Roboto'), ('Montserrat, sans-serif', 'Montserrat'), ('Lora, serif', 'Lora')], default='Inter, sans-serif', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_aria_label',
            field=models.CharField(blank=True, default='Premium architecture homepage banner', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_background_alt',
            field=models.CharField(blank=True, default='Homepage hero background image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_heading',
            field=models.TextField(blank=True, default='Designing spaces\nthat feel timeless\nand profoundly modern.', help_text='Use line breaks to control the heading layout.', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_primary_cta_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_primary_cta_text',
            field=models.CharField(blank=True, default='Explore Projects', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_secondary_cta_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_secondary_cta_text',
            field=models.CharField(blank=True, default='Book a Consultation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_stat_1_label',
            field=models.CharField(blank=True, default='Completed works', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_stat_1_value',
            field=models.CharField(blank=True, default='120+', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_stat_2_label',
            field=models.CharField(blank=True, default='Years of practice', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_stat_2_value',
            field=models.CharField(blank=True, default='18', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_stat_3_label',
            field=models.CharField(blank=True, default='Global awards', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_stat_3_value',
            field=models.CharField(blank=True, default='9', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_subheading',
            field=models.TextField(blank=True, default='A premium architecture studio shaping residential, commercial, and cultural environments with clarity, precision, and quiet confidence.', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='muted_color',
            field=models.CharField(blank=True, default='rgba(255, 255, 255, 0.78)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='overlay_color',
            field=models.CharField(blank=True, default='rgba(9, 10, 12, 0.45)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='overlay_deep_color',
            field=models.CharField(blank=True, default='rgba(9, 10, 12, 0.66)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/material_stack/'),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='number',
            field=models.CharField(blank=True, default='01 / CONCEPT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='home.materialstacksection'),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialstacksection',
            name='eyebrow',
            field=models.CharField(blank=True, default='Unique Proposition', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialstacksection',
            name='title',
            field=models.CharField(blank=True, default='The Science of Pure Form', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rippledifferencesection',
            name='button_text',
            field=models.CharField(blank=True, default='Learn More About Us', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rippledifferencesection',
            name='button_url',
            field=models.CharField(blank=True, default='/about/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rippledifferencesection',
            name='description',
            field=models.TextField(blank=True, default="We don't just build structures; we curate experiences. Our studio combines rigorous technical expertise with a profound understanding of spatial psychology.", null=True),
        ),
        migrations.AlterField(
            model_name='rippledifferencesection',
            name='feature_one_description',
            field=models.TextField(blank=True, default='Every angle, joint, and material transition is calculated with obsessive attention to detail, ensuring flawless execution.', null=True),
        ),
        migrations.AlterField(
            model_name='rippledifferencesection',
            name='feature_one_title',
            field=models.CharField(blank=True, default='Precision Engineering', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rippledifferencesection',
            name='feature_two_description',
            field=models.TextField(blank=True, default='We integrate passive cooling, natural lighting, and ethical materials to minimize environmental impact without sacrificing luxury.', null=True),
        ),
        migrations.AlterField(
            model_name='rippledifferencesection',
            name='feature_two_title',
            field=models.CharField(blank=True, default='Sustainable Integration', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rippledifferencesection',
            name='heading',
            field=models.CharField(blank=True, default='Elevating standards through visionary design.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rippledifferencesection',
            name='subtitle',
            field=models.CharField(blank=True, default='The Ripple Difference', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='home.teamsectionsettings'),
        ),
        migrations.AlterField(
            model_name='teamsectionsettings',
            name='eyebrow',
            field=models.CharField(blank=True, default='The Studio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teamsectionsettings',
            name='heading',
            field=models.CharField(blank=True, default='Our Collective', max_length=200, null=True),
        ),
    ]
