# Generated by Django 5.1.4 on 2026-05-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_materialstackcard_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialStackCard',
        ),
        migrations.DeleteModel(
            name='MaterialStackSection',
        ),
    ]
