# Generated by Django 5.1.4 on 2026-05-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_materialstackcard_delete_materialstacksection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStackSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Unique Proposition', max_length=120)),
                ('title', models.CharField(default='The Science of Pure Form.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material Stack Section',
                'verbose_name_plural': 'Material Stack Section',
            },
        ),
        migrations.CreateModel(
            name='MaterialStackCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_num', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home/material_stack/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='home.materialstacksection')),
            ],
            options={
                'verbose_name': 'Material Stack Card',
                'verbose_name_plural': 'Material Stack Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
