# Generated by Django 5.1.4 on 2026-05-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_materialstacksection_materialstackcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstackcard',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/material_stack/'),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='meta_num',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='home.materialstacksection'),
        ),
        migrations.AlterField(
            model_name='materialstackcard',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialstacksection',
            name='eyebrow',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='materialstacksection',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialstacksection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
