# Generated by Django 5.1.4 on 2026-05-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_clienttestimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='font_body',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='font_display',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='font_eyebrow',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='font_panel',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='font_stats',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='font_title',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='font_ui',
        ),
    ]
