# Generated by Django 5.1.4 on 2026-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepagesettings_font_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonials_eyebrow',
            field=models.CharField(blank=True, default='Endorsements of Purity', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonials_heading',
            field=models.CharField(blank=True, default='The Chronicles', max_length=255, null=True),
        ),
    ]
