# Generated by Django 5.1.4 on 2026-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='interior/hero/')),
                ('eyebrow', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Hero Section',
                'verbose_name_plural': 'Interior Hero Sections',
            },
        ),
    ]
