# Generated by Django 5.1.4 on 2026-05-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorPhilosophySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('paragraph_one', models.TextField(blank=True)),
                ('paragraph_two', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Philosophy Section',
                'verbose_name_plural': 'Interior Philosophy Sections',
            },
        ),
        migrations.CreateModel(
            name='InteriorPhilosophyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='interior.interiorphilosophysection')),
            ],
            options={
                'verbose_name': 'Interior Philosophy Point',
                'verbose_name_plural': 'Interior Philosophy Points',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InteriorPhilosophyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='interior/philosophy/images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='interior.interiorphilosophysection')),
            ],
            options={
                'verbose_name': 'Interior Philosophy Image',
                'verbose_name_plural': 'Interior Philosophy Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
