# Generated by Django 5.1.4 on 2026-05-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0002_interiorphilosophysection_interiorphilosophypoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Interior Service',
                'verbose_name_plural': 'Interior Services',
                'ordering': ['order'],
            },
        ),
    ]
