# Generated by Django 5.1.4 on 2026-05-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0003_interiorservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorSelectedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='interior/selected_work/main/')),
                ('side_image_1', models.ImageField(blank=True, null=True, upload_to='interior/selected_work/side/')),
                ('side_image_2', models.ImageField(blank=True, null=True, upload_to='interior/selected_work/side/')),
                ('main_title', models.CharField(blank=True, max_length=255, null=True)),
                ('main_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('side_title_1', models.CharField(blank=True, max_length=255, null=True)),
                ('side_subtitle_1', models.CharField(blank=True, max_length=255, null=True)),
                ('side_title_2', models.CharField(blank=True, max_length=255, null=True)),
                ('side_subtitle_2', models.CharField(blank=True, max_length=255, null=True)),
                ('main_desc', models.TextField(blank=True, null=True)),
                ('side_desc_1', models.TextField(blank=True, null=True)),
                ('side_desc_2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Selected Work',
                'verbose_name_plural': 'Interior Selected Works',
            },
        ),
    ]
