# Generated by Django 5.1.4 on 2026-05-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0004_interiorselectedwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='interior/gallery/')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('luxury', 'Luxury'), ('office', 'Office'), ('minimal', 'Minimal')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Gallery Item',
                'verbose_name_plural': 'Interior Gallery Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
