# Generated by Django 5.1.4 on 2026-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0005_interiorgalleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorGalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Gallery Category',
                'verbose_name_plural': 'Interior Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='interiorgalleryitem',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
