# Generated by Django 5.1.4 on 2026-05-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0006_interiorgallerycategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interiorgalleryitem',
            name='category',
        ),
        migrations.AddField(
            model_name='interiorgalleryitem',
            name='gallery_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='interior.interiorgallerycategory'),
        ),
    ]
