# Generated by Django 5.1.4 on 2026-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('eyebrow', models.CharField(default='ABOUT THE STUDIO', max_length=120)),
                ('title', models.TextField(default='Designing spaces\nwith clarity, restraint,\nand timeless intention.', help_text='Use line breaks for multi-line hero titles.')),
                ('description', models.TextField(default='We create architecture that balances atmosphere, functionality, and material honesty — shaping environments that feel calm, refined, and enduring.')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('primary_button_text', models.CharField(default='Our Philosophy', max_length=100)),
                ('primary_button_url', models.CharField(blank=True, default='#', max_length=300)),
                ('secondary_button_text', models.CharField(default='View Projects', max_length=100)),
                ('secondary_button_url', models.CharField(blank=True, default='#', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Hero Section',
                'verbose_name_plural': 'About Hero Section',
            },
        ),
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='About Us', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='Ripple Architecture & Design About Page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
    ]
