# Generated by Django 5.1.4 on 2026-05-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutherosection_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOverviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide the overview section.')),
                ('subtitle', models.CharField(default='Firm Overview', help_text='Small upper heading above the title.', max_length=120)),
                ('title', models.CharField(default='Designing spaces with purpose. Creating a continuous ripple in modern living.', help_text='Main overview heading.', max_length=300)),
                ('description', models.TextField(default='We believe in an architectural philosophy that bridges the gap between the built environment and human experience. By eliminating rigid boundaries and uncompromising constraints, we shape fluid, dynamic spaces tailored to exact specifications.', help_text='Overview section description.')),
                ('button_text', models.CharField(blank=True, default='Discover Our Studio', max_length=100)),
                ('button_link', models.CharField(blank=True, default='#studio', max_length=300)),
                ('main_image', models.ImageField(blank=True, help_text='Primary overview image.', null=True, upload_to='about/overview/')),
                ('secondary_image', models.ImageField(blank=True, help_text='Secondary overlapping image.', null=True, upload_to='about/overview/')),
                ('main_image_alt', models.CharField(blank=True, default='Modern architectural exterior with clean lines', max_length=200)),
                ('secondary_image_alt', models.CharField(blank=True, default='Refined interior design detailing', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Overview Section',
                'verbose_name_plural': 'About Overview Section',
            },
        ),
    ]
