# Generated by Django 5.1.4 on 2026-05-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutoverviewsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMissionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Vision, Mission & Values', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('vision_title', models.CharField(default='Vision', max_length=100)),
                ('vision_text', models.TextField()),
                ('vision_icon', models.CharField(default='fa-solid fa-eye', help_text='FontAwesome class', max_length=100)),
                ('mission_title', models.CharField(default='Mission', max_length=100)),
                ('mission_text', models.TextField()),
                ('mission_icon', models.CharField(default='fa-solid fa-compass', help_text='FontAwesome class', max_length=100)),
                ('values_title', models.CharField(default='Values', max_length=100)),
                ('values_text', models.TextField()),
                ('values_icon', models.CharField(default='fa-solid fa-gem', help_text='FontAwesome class', max_length=100)),
            ],
            options={
                'verbose_name': 'Vision Mission Values',
                'verbose_name_plural': 'Vision Mission Values',
            },
        ),
    ]
