# Generated by Django 5.1.4 on 2026-05-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_visionmissionvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStatsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Numbers That Define Our Architectural Journey', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='A reflection of our commitment to precision, innovation, and timeless architectural excellence.')),
                ('tag', models.CharField(default='OUR IMPACT', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Key Stats Section',
                'verbose_name_plural': 'Key Stats Section',
            },
        ),
        migrations.CreateModel(
            name='KeyStatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, default='+', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='about.keystatssection')),
            ],
            options={
                'verbose_name': 'Key Stat Item',
                'verbose_name_plural': 'Key Stat Items',
                'ordering': ['order'],
            },
        ),
    ]
