# Generated by Django 5.1.4 on 2026-05-11 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_keystatssection_keystatitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedWithSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this section.')),
                ('kicker', models.CharField(default='We collaborate with', help_text='Small upper heading text.', max_length=100)),
                ('heading', models.CharField(default='We are associated with', help_text='Main section heading.', max_length=200)),
                ('description', models.TextField(default='Trusted partners and global platforms that contribute to our design, technology, and execution excellence.', help_text='Section description text.')),
                ('section_padding_top', models.PositiveIntegerField(default=110, help_text='Top spacing in px.')),
                ('section_padding_bottom', models.PositiveIntegerField(default=110, help_text='Bottom spacing in px.')),
                ('marquee_speed', models.PositiveIntegerField(default=22, help_text='Animation duration in seconds.')),
            ],
            options={
                'verbose_name': 'Associated With Section',
                'verbose_name_plural': 'Associated With Section',
            },
        ),
        migrations.CreateModel(
            name='AssociatedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner or company name.', max_length=150)),
                ('logo', models.ImageField(help_text='Upload partner logo.', upload_to='about/associated_partners/')),
                ('website_url', models.URLField(blank=True, help_text='Optional partner website URL.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number appears first.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this partner.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='about.associatedwithsection')),
            ],
            options={
                'verbose_name': 'Associated Partner',
                'verbose_name_plural': 'Associated Partners',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
