# Generated by Django 5.1.4 on 2026-05-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_associatedwithsection_associatedpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedpartner',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='associatedpartner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='associatedpartner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='about/associated_partners/'),
        ),
        migrations.AlterField(
            model_name='associatedpartner',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='associatedpartner',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='about.associatedwithsection'),
        ),
        migrations.AlterField(
            model_name='associatedpartner',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='associatedwithsection',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='associatedwithsection',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='associatedwithsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='associatedwithsection',
            name='kicker',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='associatedwithsection',
            name='marquee_speed',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='associatedwithsection',
            name='section_padding_bottom',
            field=models.PositiveIntegerField(default=110),
        ),
        migrations.AlterField(
            model_name='associatedwithsection',
            name='section_padding_top',
            field=models.PositiveIntegerField(default=110),
        ),
    ]
