# Generated by Django 5.1.4 on 2026-05-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_referral_lead_scale_lead_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('quote', 'RFQ'), ('contact', 'Contact'), ('website', 'Website'), ('ad', 'Ad Campaign'), ('whatsapp', 'WhatsApp'), ('subscription', 'Subscription')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('quote', 'RFQ Form'), ('contact', 'Contact Form'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('subscription', 'Subscription Footer')], default='website', max_length=20),
        ),
    ]
